[project]
name = "flex-dl"
version = "0.1.1"
description = "CLI tool and Python library for downloading media content from flex-kino.com"
authors = [
    { name = "n.denissov", email = "n.denissov@proton.me" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Multimedia :: Video",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = []

[project.scripts]
flex-dl = "flex_dl.__main__:main"

[project.urls]
Homepage = "https://github.com/ndenissov/flex-dl"
Repository = "https://github.com/ndenissov/flex-dl"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "flex_dl" }]
